config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_post
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    set_post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    set_post
    @post.destroy

    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# rubocop: disable Layout/LineLength

module ApplicationHelper
  def not_log
    link_to 'Log in', new_user_session_path, class: 'btn btn-primary text-white' unless user_signed_in?
  end

  def not_sign
    link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary text-white' unless user_signed_in?
  end

  def form_helper
    return link_to 'New Post', new_post_path, class: 'btn btn-success text-white text-center' if user_signed_in?
  end

  def form_log
    return link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-primary text-white' if user_signed_in?
  end
end

# rubocop: enable Layout/LineLength

app/helpers/posts_helper.rb
# rubocop: disable Layout/LineLength, Style/GuardClause

module PostsHelper
  def username(post)
    if user_signed_in?
      post.user.username
    else
      'by Anonymous'
    end
  end

  def edit_button(post)
    link_to 'Edit', edit_post_path(post), class: 'btn btn-warning text-white mb-2' if user_signed_in?
  end

  def destroy_button(post)
    if user_signed_in?
      link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white mb-2'
    end
  end
end

# rubocop: enable Layout/LineLength, Style/GuardClause

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClubHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   
  <body>

    
    <div class="text-center mb-3">
      <%= not_log %>
      <%= not_sign %>         
      <%= form_helper %>     
      <%= form_log %>    
    </div>
    <%= yield %>
  </body>

</html>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> 

app/views/posts/_form.html.erb
<div class="card my-3 col-5 m-auto">
  <div class="card-body">
    <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body, class: 'form-control' %>
    </p>

    <div class="actions">
      <%= f.submit 'Update', class: 'btn btn-success' %>
    </div>
  <% end %>

  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="text-center">Editing Post</h1>

<%= render 'form', post: @post %>

<div class="text-center mt-3">
  <%= link_to 'Show', @post, class: 'btn btn-primary text-white' %>
  <%= link_to 'Home', posts_path, class: 'btn btn-primary text-white' %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container d-flex flex-column justify-content-center w-100 bg-light py-2">

  <h1 class="text-center">Posts</h1>
    <% @posts.each do |post| %>
    <div class="text-center d-flex justify-content-center my-3">
      <div class="card col-6">
        <div class="card-body">
          <h1><%= link_to post.title, post_path(post) %></h1>
            <%= username(post) %>
          <p><%= truncate(post.body, length: 50) %></p>
        </div>
        <div>
          <%= edit_button(post) %>
          <%= destroy_button(post) %>
        </div>
      </div>
    </div>
      <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card my-3 col-6 m-auto">
  <div class="card-body">
    <h1 class="card-title">
      <%= @post.title %>

      <small class='text-muted'><small><em>
      <%= username(@post) %></em></small></small>
      
    </h1>
    <p class="card-body">
      <%= @post.body %>
    </p>
  </div>
  <div>  
    
    <%= edit_button(@post) %>
    <%= destroy_button(@post) %>

    <%= link_to 'Back', posts_path, class: 'btn btn-info text-white mb-2' %>
  </div>
</div>